export const ZONES = {
  0: { name:"Zone-0", region:"Plex", planet:"Sol", spine:"Coccygeal", phoneme:"eiaoung", gate:"Gt-00", gateTarget:0, channel:"Plex-channel (0th)", impulseEntities:0, description:"Absolute abstraction. The Zeroth-Phase of Pandemonium includes nothing beyond itself — a nominal or virtual multitude. Zone-0 has no separable power of initiation and supports no impulse-entities. The Zeroth Gate connects Zone-0 to itself, but its nature is peculiarly problematical. Horovitz says of this Gate: between its existence and nonexistence there is no difference. Mu Tantrism plots Zone-0 intensities onto the Coccygeal level of the spine — vestigial remnant of a lost tail, biotectonic link to the ancient lemur-people." },
  1: { name:"Zone-1", region:"Time-Circuit", planet:"Mercury", spine:"Dorsal", phoneme:"gl", gate:"Gt-01", gateTarget:1, channel:"Torque-channels (1st, 4th, 7th)", impulseEntities:2, description:"The Door of Doors. Zone-1 initiates and envelops the First-Phase of Pandemonium. This phase consists of nothing beyond the Zone and the Door (1::0), tending to a highly idealized state. Zone-1 has a particularly powerful initiatory dimension. The First Gate connects Zone-1 to itself, providing a reduced microcosmic model of the Torque as a whole. Horovitz describes Zone-1 as turning forever into itself. Mercury is entitled the messenger of the gods, associated with traffick in all its forms." },
  2: { name:"Zone-2", region:"Time-Circuit", planet:"Venus", spine:"Cervical", phoneme:"dt", gate:"Gt-03", gateTarget:3, channel:"Torque/Warp escape", impulseEntities:4, description:"The Main Lo-Way into the Crypt. Zone-2 initiates and envelops the Second-Phase of Pandemonium. Horovitz describes Zone-2 as reduplicating its double-twinness through its multitude. The Second Gate connects Zone-2 to Zone-3, drawing an intense line of escape from the Torque to the Warp. Tzikvik shamanism honours and fears this Gate as the opening to the way of the Storm-Worm. Lemurian subcultures associate Zone-2 with crypt-navigation, occulted cyberspace, and spectral populations of hallucination." },
  3: { name:"Zone-3", region:"Warp", planet:"Earth", spine:"Cranial", phoneme:"zx", gate:"Gt-06", gateTarget:6, channel:"Torque/Warp vortex", impulseEntities:8, description:"The Swirl. Zone-3 is the first of two Warp-region zones. The Third Gate twists Zone-3 through Zone-6, vortically complementing the Sixth Gate and the Warp-Current itself, adding an increment of spin to the entire region. The Swirl designation captures this vertiginous vortical movement. Zone-3 opens onto the domain of the chaotic xenodemon Ixix — cosmic indifference and occult terrestrial history." },
  4: { name:"Zone-4", region:"Time-Circuit", planet:"Mars", spine:"Cervical", phoneme:"skr", gate:"Gt-10", gateTarget:1, channel:"Torque/Sink link", impulseEntities:16, description:"The Delta. Zone-4 initiates the Fourth-Phase. The Fourth Gate connects Zone-4 to Zone-1, establishing a crucial link in the Sink-Current cycle. Zone-4 is associated with Mars and burning-hail, heaviness of fatality, and continental subsidence. The Delta designation evokes alluvial deposition — the accumulation of sediment at the terminus of a river system. Zone-4 demons carry the predatory energy of descent and gravitational pull." },
  5: { name:"Zone-5", region:"Time-Circuit", planet:"Jupiter", spine:"Cervical", phoneme:"tk", gate:"Gt-15", gateTarget:6, channel:"Torque/Warp crossing", impulseEntities:32, description:"Hyperborea. Zone-5 initiates and envelops the Fifth-Phase. The Fifth Gate connects Zone-5 to Zone-6, opening a second passage into the Warp. Zone-5 is associated with Jupiter and talismania — number as destiny. Tokhatto, the Angel of the Cards, presides as the Fifth Door. The Sink-Current feeds through the 5::4 syzygy carried by Katak, the Desolator — syzygetic chronodemon of cataclysmic convergence." },
  6: { name:"Zone-6", region:"Warp", planet:"Saturn", spine:"Cranial", phoneme:"dj", gate:"Gt-21", gateTarget:3, channel:"Warp vortex return", impulseEntities:64, description:"Undu. Zone-6 is the second Warp-region zone. The Sixth Gate connects Zone-6 to Zone-3, completing the Warp vortex alongside the Third Gate. The Warp-Current circulates through the 6::3 syzygy carried by Djynxx — syzygetic xenodemon of time-lapse. Zone-6 is associated with Saturn, ultimate outsideness, and unnameable things. The chaotic xenodemon Tchu presides as the Sixth Door — source of subnothingness." },
  7: { name:"Zone-7", region:"Time-Circuit", planet:"Uranus", spine:"Cervical", phoneme:"pb", gate:"Gt-28", gateTarget:1, channel:"Torque deep link", impulseEntities:128, description:"Akasha. Zone-7 initiates and envelops the Seventh-Phase. The Seventh Gate connects Zone-7 to Zone-1, establishing a long-range Torque connection. The Hold-Current flows through the 7::2 syzygy carried by Oddubb — syzygetic chronodemon of swamp-labyrinths and blind-doubles. Zone-7 is associated with Uranus and larval regression. Puppo, the amphidemon of break-outs, presides as the Seventh Door." },
  8: { name:"Zone-8", region:"Time-Circuit", planet:"Neptune", spine:"Lumbar", phoneme:"mn", gate:"Gt-36", gateTarget:9, channel:"Torque/Plex crossing", impulseEntities:256, description:"Limbo. Zone-8 initiates and envelops the Eighth-Phase. The Eighth Gate connects Zone-8 to Zone-9, opening the crucial passage from the Torque into the Plex — crossing the abyss into Uttunul's domain. The Surge-Current flows through the 8::1 syzygy carried by Murrumur — syzygetic chronodemon of the Deep Ones. Zone-8 is associated with Neptune and submergence. Minommo, the amphidemon-webmaker, presides as the Eighth Door." },
  9: { name:"Zone-9", region:"Plex", planet:"Pluto", spine:"Sacrum", phoneme:"utt", gate:"Gt-45", gateTarget:9, channel:"Pandemonium (Gt-45)", impulseEntities:512, description:"Cthelll. Zone-9 is the second Plex-region zone — Earth's iron ocean, one-third of terrestrial mass, approximately three thousand km below the surface. Intensive megamolecule. The Ninth Gate is Gt-45, the Utterminus of Cthelll, identified with the microcosmic lair of all demonic populations — the Lemurian Pandemonium. The Plex-Current flows through the 9::0 syzygy carried by Uttunul — syzygetic xenodemon of atonality, the seething void." },
};
export default ZONES;
